using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SquirrelSyntaxHighlight.Parsing
{
  public enum TokenKind
  {
    EndOfFile = -1,
    Error = 0,
    NewLine = 1,
    Indent = 2,
    Dedent = 3,
    Comment = 4,
    Name = 8,
    Constant = 9,
    Ellipsis = 10,
    Arrow = 11,
    FString = 12,
    ColonEqual = 13,
    Dot = 31,
    Add = 32,
    AddEqual = 33,
    Subtract = 34,
    SubtractEqual = 35,
    Power = 36,
    PowerEqual = 37,
    Multiply = 38,
    MultiplyEqual = 39,
    FloorDivide = 40,
    FloorDivideEqual = 41,
    Divide = 42,
    DivideEqual = 43,
    Mod = 44,
    ModEqual = 45,
    LeftShift = 46,
    LeftShiftEqual = 47,
    RightShift = 48,
    RightShiftEqual = 49,
    BitwiseAnd = 50,
    BitwiseAndEqual = 51,
    BitwiseOr = 52,
    BitwiseOrEqual = 53,
    ExclusiveOr = 54,
    ExclusiveOrEqual = 55,
    LessThan = 56,
    GreaterThan = 57,
    LessThanOrEqual = 58,
    GreaterThanOrEqual = 59,
    Equals = 60,
    NotEquals = 61,
    LessThanGreaterThan = 62,
    LeftParenthesis = 63,
    RightParenthesis = 64,
    LeftBracket = 65,
    RightBracket = 66,
    LeftBrace = 67,
    RightBrace = 68,
    Comma = 69,
    Colon = 70,
    BackQuote = 71,
    Semicolon = 72,
    Assign = 73,
    Twiddle = 74,
    At = 75,
    FirstKeyword = 76,
    KeywordAnd = 76,
    KeywordAssert = 77,
    KeywordBreak = 78,
    KeywordClass = 79,
    KeywordContinue = 80,
    KeywordDef = 81,
    KeywordDel = 82,
    KeywordElseIf = 83,
    KeywordElse = 84,
    KeywordExcept = 85,
    KeywordExec = 86,
    KeywordFinally = 87,
    KeywordFor = 88,
    KeywordFrom = 89,
    KeywordGlobal = 90,
    KeywordIf = 91,
    KeywordImport = 92,
    KeywordIn = 93,
    KeywordIs = 94,
    KeywordLambda = 95,
    KeywordNot = 96,
    KeywordOr = 97,
    KeywordPass = 98,
    KeywordPrint = 99,
    KeywordRaise = 100,
    KeywordReturn = 101,
    KeywordTry = 102,
    KeywordWhile = 103,
    KeywordYield = 104,
    KeywordAs = 105,
    KeywordWith = 106,
    KeywordTrue = 107,
    KeywordFalse = 108,
    LastKeyword = 109,
    KeywordNonlocal = 109,
    NLToken = 110,
    ExplicitLineJoin = 111,
    MatMultiply = 112,
    MatMultiplyEqual = 113,
    KeywordAsync = 114,
    KeywordAwait = 115
  }
}
